# Generated by Django 6.0.4 on 2026-10-05 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScreeningResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_score", models.FloatField(default=0)),
                ("ml_score", models.FloatField(default=0)),
                ("nlp_score", models.FloatField(default=0)),
                ("dl_score", models.FloatField(default=0)),
                ("final_score", models.FloatField(default=0)),
                ("prediction", models.CharField(blank=True, max_length=50)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screening_result",
                        to="candidates.candidate",
                    ),
                ),
            ],
        ),
    ]
