VIEW_CANDIDATE = 'VIEW_CANDIDATE'
CREATE_CANDIDATE = 'CREATE_CANDIDATE'
EDIT_CANDIDATE = 'EDIT_CANDIDATE'
DELETE_CANDIDATE = 'DELETE_CANDIDATE'

UPLOAD_CANDIDATES = 'UPLOAD_CANDIDATES'

SCREEN_CANDIDATE = 'SCREEN_CANDIDATE'
VIEW_SCREENING = 'VIEW_SCREENING'

MANAGE_INTERVIEW = 'MANAGE_INTERVIEW'
SUBMIT_FEEDBACK = 'SUBMIT_FEEDBACK'

VIEW_DASHBOARD = 'VIEW_DASHBOARD'